name: E2E
on:
  workflow_dispatch:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the codebase
      uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: 3.8.9
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Docker Compose
      run: |
        cp tests/docker-compose.yml .
        docker-compose up -d
